redis:
  single:
    host: 39.106.171.124
    database: 6
    password: 6Kgvd4BzNIX1
    port: 6789
  cluster:
    password: sword-cluster
    nodes:
      - 39.106.171.124:30001
      - 39.106.171.124:30002
      - 39.106.171.124:30003
      - 39.106.171.124:30004
      - 39.106.171.124:30005
      - 39.106.171.124:30006
  sentinel:
    master: mymaster
    nodes:
      - 172.17.151.233:26579
      - 172.17.151.233:26679
#    password: sentinel-36379
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.17.151.233:3306/exercise?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

domain: http://172.17.151.233:9090/short/
daily:
  invoke:
    limit: 10000
    qps: 1000
server:
  port: 9090
logback:
  common:
    level: info
  root:
    level: error
