redis:
  single:
    host: 192.168.1.128
    database: 6
    timeout: 3000
    password: 6Kgvd4BzNIX1
    port: 6789
  cluster:
    password: sword-cluster
    nodes:
      - 172.23.23.133:30001
      - 172.23.23.133:30002
      - 172.23.23.133:30003
      - 172.23.23.133:30004
      - 172.23.23.133:30005
      - 172.23.23.133:30006
  sentinel:
    master: mymaster
    nodes:
      - 172.23.23.133:46380
      - 172.23.23.133:46381
    password: sentinel-36379
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.128:3306/exercise?serverTimezone=GMT
    username: root
    password: 123qewQWE!@#
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

domain: http://192.168.1.15:8080/short/
daily:
  invoke:
    limit: 100
    qps: 10
server:
  port: 8080
logback:
  common:
    level: info
  root:
    level: error
